import vitestPlugin from "@vitest/eslint-plugin";
import type {Linter} from "eslint";

import {TYPESCRIPT_TEST_FILES} from "../constants";

const vitestRules: Linter.RulesRecord = {
  "vitest/consistent-test-it": ["error", {fn: "it", withinDescribe: "it"}],
  "vitest/consistent-vitest-vi": ["error", {fn: "vi"}],
  "vitest/expect-expect": "error",
  "vitest/hoisted-apis-on-top": "error",
  "vitest/no-alias-methods": "error",
  "vitest/no-commented-out-tests": "error",
  "vitest/no-conditional-expect": "error",
  "vitest/no-conditional-in-test": "error",
  "vitest/no-conditional-tests": "error",
  "vitest/no-disabled-tests": "error",
  "vitest/no-done-callback": "error",
  "vitest/no-duplicate-hooks": "error",
  "vitest/no-focused-tests": "error",
  "vitest/no-identical-title": "error",
  "vitest/no-import-node-test": "error",
  "vitest/no-interpolation-in-snapshots": "error",
  "vitest/no-mocks-import": "error",
  "vitest/no-standalone-expect": "error",
  "vitest/no-test-prefixes": "error",
  "vitest/no-test-return-statement": "error",
  "vitest/no-unneeded-async-expect-function": "error",
  "vitest/padding-around-after-all-blocks": "error",
  "vitest/padding-around-after-each-blocks": "error",
  "vitest/padding-around-before-all-blocks": "error",
  "vitest/padding-around-before-each-blocks": "error",
  "vitest/padding-around-describe-blocks": "error",
  "vitest/padding-around-test-blocks": "error",
  "vitest/prefer-called-exactly-once-with": "error",
  "vitest/prefer-called-with": "error",
  "vitest/prefer-comparison-matcher": "error",
  "vitest/prefer-each": "error",
  "vitest/prefer-equality-matcher": "error",
  "vitest/prefer-expect-resolves": "error",
  "vitest/prefer-expect-type-of": "error",
  "vitest/prefer-hooks-in-order": "error",
  "vitest/prefer-hooks-on-top": "error",
  "vitest/prefer-import-in-mock": "error",
  "vitest/prefer-lowercase-title": ["error", {ignore: ["describe"]}],
  "vitest/prefer-mock-promise-shorthand": "error",
  "vitest/prefer-mock-return-shorthand": "error",
  "vitest/prefer-spy-on": "error",
  "vitest/prefer-strict-boolean-matchers": "error",
  "vitest/prefer-to-be": "error",
  "vitest/prefer-to-be-object": "error",
  "vitest/prefer-to-contain": "error",
  "vitest/prefer-to-have-been-called-times": "error",
  "vitest/prefer-to-have-length": "error",
  "vitest/prefer-todo": "error",
  "vitest/prefer-vi-mocked": "error",
  "vitest/require-awaited-expect-poll": "error",
  "vitest/require-hook": "error",
  "vitest/require-local-test-context-for-concurrent-snapshots": "error",
  "vitest/require-top-level-describe": "error",
  "vitest/valid-describe-callback": "error",
  "vitest/valid-expect": ["error", {maxArgs: 2}],
  "vitest/valid-expect-in-promise": "error",
  "vitest/valid-title": "error",
};

export const vitest: Linter.Config[] = [
  {
    files: TYPESCRIPT_TEST_FILES,
    name: "yarapa/vitest",
    plugins: {vitest: vitestPlugin},
    rules: vitestRules,
  },
];
