import type {Linter} from "eslint";

import {JAVASCRIPT_AND_TYPESCRIPT_FILES} from "../constants";

import {PREFER_NUMBER_IS_FINITE_MESSAGE, PREFER_NUMBER_IS_NAN_MESSAGE} from "./base.constant";

const coreRules: Linter.RulesRecord = {
  "constructor-super": "error",
  "default-case-last": "error",
  "for-direction": "error",
  "getter-return": "error",
  "grouped-accessor-pairs": "error",
  "guard-for-in": "error",
  "no-alert": "error",
  "no-async-promise-executor": "error",
  "no-await-in-loop": "error",
  "no-caller": "error",
  "no-case-declarations": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": "error",
  "no-constructor-return": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-delete-var": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-empty-static-block": "error",
  "no-ex-assign": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-extra-boolean-cast": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-global-assign": "error",
  "no-import-assign": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-iterator": "error",
  "no-label-var": "error",
  "no-lone-blocks": "error",
  "no-loop-func": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-multi-str": "error",
  "no-new": "error",
  "no-new-native-nonconstructor": "error",
  "no-nonoctal-decimal-escape": "error",
  "no-obj-calls": "error",
  "no-octal": "error",
  "no-octal-escape": "error",
  "no-promise-executor-return": "error",
  "no-proto": "error",
  "no-prototype-builtins": "error",
  "no-redeclare": "error",
  "no-regex-spaces": "error",
  "no-script-url": "error",
  "no-self-assign": "error",
  "no-sequences": "error",
  "no-setter-return": "error",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "error",
  "no-this-before-super": "error",
  "no-unassigned-vars": "error",
  "no-undef": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-labels": "error",
  "no-unused-private-class-members": "error",
  "no-unused-vars": "error",
  "no-useless-assignment": "error",
  "no-useless-backreference": "error",
  "no-useless-catch": "error",
  "no-useless-computed-key": "error",
  "no-useless-concat": "error",
  "no-useless-escape": "error",
  "no-useless-rename": "error",
  "no-with": "error",
  "prefer-numeric-literals": "error",
  "preserve-caught-error": "error",
  "require-yield": "error",
  "symbol-description": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
  yoda: "error",
};

const modernJavaScriptRules: Linter.RulesRecord = {
  "arrow-body-style": ["error", "as-needed", {requireReturnForObjectLiteral: false}],
  "class-methods-use-this": "error",
  "consistent-return": "error",
  curly: ["error", "all"],
  "default-case": [
    "error",
    {
      commentPattern: "^no default$",
    },
  ],
  "default-param-last": "error",
  "dot-notation": "error",
  eqeqeq: ["error", "always"],
  "func-names": ["error", "as-needed"],
  "max-classes-per-file": ["error", 1],
  "new-cap": [
    "error",
    {
      capIsNew: false,
      capIsNewExceptions: ["Immutable.Map", "Immutable.Set", "Immutable.List"],
      newIsCap: true,
      newIsCapExceptions: [],
    },
  ],
  "no-array-constructor": "error",
  "no-continue": "error",
  "no-else-return": [
    "error",
    {
      allowElseIf: false,
    },
  ],
  "no-empty-function": "error",
  "no-inline-comments": "error",
  "no-inner-declarations": "error",
  "no-multi-assign": "error",
  "no-object-constructor": "error",
  "no-plusplus": "error",
  "no-restricted-properties": [
    "error",
    {
      message: "arguments.callee is deprecated",
      object: "arguments",
      property: "callee",
    },
    {
      message: PREFER_NUMBER_IS_FINITE_MESSAGE,
      object: "global",
      property: "isFinite",
    },
    {
      message: PREFER_NUMBER_IS_FINITE_MESSAGE,
      object: "self",
      property: "isFinite",
    },
    {
      message: PREFER_NUMBER_IS_FINITE_MESSAGE,
      object: "window",
      property: "isFinite",
    },
    {
      message: PREFER_NUMBER_IS_NAN_MESSAGE,
      object: "global",
      property: "isNaN",
    },
    {
      message: PREFER_NUMBER_IS_NAN_MESSAGE,
      object: "self",
      property: "isNaN",
    },
    {
      message: PREFER_NUMBER_IS_NAN_MESSAGE,
      object: "window",
      property: "isNaN",
    },
  ],
  "no-return-assign": ["error", "always"],
  "no-underscore-dangle": [
    "error",
    {
      allow: [],
      allowAfterSuper: false,
      allowAfterThis: false,
      enforceInMethodNames: true,
    },
  ],
  "no-unneeded-ternary": ["error", {defaultAssignment: false}],
  "no-var": "error",
  "no-warning-comments": ["error", {location: "anywhere", terms: ["todo", "fixme", "xxx"]}],
  "object-shorthand": ["error", "always"],
  "one-var": ["error", "never"],
  "operator-assignment": ["error", "always"],
  "prefer-arrow-callback": ["error", {allowNamedFunctions: false, allowUnboundThis: true}],
  "prefer-const": "error",
  "prefer-destructuring": [
    "error",
    {
      AssignmentExpression: {array: true, object: true},
      VariableDeclarator: {array: false, object: true},
    },
    {enforceForRenamedProperties: false},
  ],
  "prefer-exponentiation-operator": "error",
  "prefer-object-has-own": "error",
  "prefer-object-spread": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  radix: "error",
  "vars-on-top": "error",
};

export const base: Linter.Config[] = [
  {
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    name: "yarapa/base/linter-options",
  },
  {
    files: JAVASCRIPT_AND_TYPESCRIPT_FILES,
    name: "yarapa/base/core",
    rules: coreRules,
  },
  {
    files: JAVASCRIPT_AND_TYPESCRIPT_FILES,
    name: "yarapa/base/modern-js",
    rules: modernJavaScriptRules,
  },
];
